Select 

    trim(mx_last_contacted_action_code) as mx_last_contacted_action_code,
    trim(mx_bank_lan) as mx_bank_lan,
    trim(mx_tls_name) as mx_tls_name,
    trim(mx_borrower_ac_holding_branch) as mx_borrower_ac_holding_branch,
    mx_number_of_attempts,
    trim(mx_system_generated_lan) as mx_system_generated_lan,
    mx_number_of_call_backs,
    trim(mx_loan_account_number) as mx_loan_account_number,
    mx_total_payment_till_now,
    trim(mx_trust_name_bank_name) as mx_trust_name_bank_name,
    mx_pinstid,
    trim(mx_current_allocation_user_name) as mx_current_allocation_user_name,
    cast(mx_tos_updated as date) as mx_tos_updated,
    mx_amount_agreed_for_payment,
    mx_principal_outstanding,
    trim(mx_type_of_loan_nature_of_facility) as mx_type_of_loan_nature_of_facility,
    trim(mx_loan_category) as mx_loan_category,
    trim(mx_status) as mx_status,
    prospectid as prospect_id,
    prospectautoid as prospect_auto_id,
    trim(firstname) as first_name,
    trim(lastname) as last_name,
    trim(emailaddress) as email_address,
    trim(prospectstage) as prospect_stage,
    ownerid as owner_id,
    cast(createdon as date) as created_on,
    trim(mx_city) as mx_city,
    trim(mx_loan_type) as mx_loan_type,
    cast(mx_promised_to_pay_date as date) as mx_promised_to_pay_date,
    mx_case_id,
    cast(mx_ots_agreed_date as date) as mx_ots_agreed_date,
    cast(mx_call_back_date as date) as mx_call_back_date,
    trim(owneridname) as owner_id_name

from {{ source('crm', 'leads') }}