Select 

    userid as user_id,
    trim(firstname) as first_name,
    trim(middlename) as middle_name,
    trim(lastname) as last_name,
    trim(emailaddress) as email_address,
    trim(city) as city,
    isdefaultowner as is_default_owner,
    isadministrator as is_administrator,
    isagencyuser as is_agency_user,
    isbillinguser as is_billing_user,
    timezone as time_zone,
    dateformat as date_format,
    signature_html as signature_html,
    trim(signature_text) as signature_text,
    trim(associatedphonenumbers) as associated_phone_numbers,
    trim(availabilitystatus) as availability_status,
    trim(teamname) as team_name,
    ischeckinenabled as is_checkin_enabled,
    ischeckedin as is_checked_in,
    cast(lastcheckedon as date) as last_checked_on,
    lastcheckedipaddress as last_checked_ip_address,
    mx_custom_1,
    mx_custom_2,
    mx_custom_3,
    mx_custom_4,
    mx_custom_5,
    mx_custom_6,
    mx_custom_7,
    mx_custom_8,
    mx_custom_9,
    mx_custom_10,
    statuscode as status_code,
    createdbyid as created_by_id,
    trim(createdbyname) as created_by_name,
    cast(createdon as date) as created_on,
    modifiedbyid as modified_by_id,
    trim(modifiedbyname) as modified_by_name,
    cast(modifiedon as date) as modified_on,
    role,
    isphonecallagent as is_phone_call_agent,
    usertype as user_type,
    managerid as manager_id,
    trim(managername) as manager_name,
    trim(manageremailaddress) as manager_email_address,
    isemailsender as is_email_sender,
    groups

from {{ source('crm', 'users') }}

